# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8395f4c498e55f5d59985dd2d9243f575ca77d94c61e19d8eb2fe61aba1b6549bcafa3311a6a45b547375d2abfafb194d5280ea08e46e9b1e15a1105b5c62ae5

test:
  secret_key_base: b059ca0e8261dd252155221fbdd7bdd7a83b6e7dafc8bf924680ba3f518ea9fc9394e8fdd5046e9f007f14fbafacf5e7cf5c049f8ec14a5604a005302079c85b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
